// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartsController from "./charts_controller"
application.register("charts", ChartsController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import FormController from "./form_controller"
application.register("form", FormController)

import NumberInputController from "./number_input_controller"
application.register("number-input", NumberInputController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
